import { useFocusEffect, useRouter } from 'expo-router';
import { useCallback, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { EmptyState, PageIntro, SectionHeading } from '@/components/ui-kit';
import { Palette } from '@/constants/theme';
import { useAuth } from '@/context/AuthContext';
import { apiFetch } from '@/lib/api';
import type { Booking, EventItem } from '@/types';

export default function DashboardScreen() {
  const { token, user } = useAuth(); const router = useRouter(); const [events, setEvents] = useState<EventItem[]>([]); const [bookings, setBookings] = useState(0);
  useFocusEffect(useCallback(() => { let active = true; if (!token) return; void apiFetch<{ events: EventItem[] }>('/organizer/events', {}, token).then(async (result) => { if (!active) return; setEvents(result.events); const lists = await Promise.all(result.events.map((event) => apiFetch<{ bookings: Booking[] }>(`/organizer/events/${event.id}/bookings`, {}, token))); if (active) setBookings(lists.reduce((sum, item) => sum + item.bookings.length, 0)); }).catch(() => { if (active) { setEvents([]); setBookings(0); } }); return () => { active = false; }; }, [token]));
  const upcoming = events.filter((event) => event.date >= new Date().toISOString().slice(0, 10)).length;
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><View style={styles.inner}><PageIntro eyebrow={`Welcome, ${user?.name?.split(' ')[0] ?? 'Organizer'}`} title="Organizer Center" description="A clear view of your events and attendees." /><View style={styles.stats}><Stat label="MY EVENTS" value={events.length} /><Stat label="UPCOMING" value={upcoming} /><Stat label="BOOKINGS" value={bookings} /></View><SectionHeading title="My events" action={<Pressable onPress={() => router.push('/my-events')}><Text style={styles.link}>Manage all</Text></Pressable>} />{events.length ? events.slice(0, 3).map((event) => <Pressable key={event.id} onPress={() => router.push({ pathname: '/event-bookings/[id]', params: { id: event.id } })} style={styles.event}><View style={styles.date}><Text style={styles.day}>{event.date.slice(8, 10)}</Text><Text style={styles.month}>{new Date(`${event.date}T00:00:00`).toLocaleString('en', { month: 'short' }).toUpperCase()}</Text></View><View style={styles.eventInfo}><Text style={styles.eventName}>{event.name}</Text><Text style={styles.eventMeta}>{event.location} · {event.availableSeats}/{event.totalSeats} available</Text></View><Text style={styles.arrow}>›</Text></Pressable>) : <EmptyState title="No events yet" message="Create your first event to start building your organizer workspace." />}<Pressable onPress={() => router.push('/create-event')} style={styles.create}><Text style={styles.createText}>+  Create Event</Text></Pressable></View></ScrollView>;
}
function Stat({ label, value }: { label: string; value: number }) { return <View style={styles.stat}><Text style={styles.statLabel}>{label}</Text><Text style={styles.statValue}>{value}</Text></View>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: Palette.background }, content: { padding: 20, paddingBottom: 36 }, inner: { width: '100%', maxWidth: 680, alignSelf: 'center' }, stats: { flexDirection: 'row', gap: 10, marginTop: 25 }, stat: { flex: 1, backgroundColor: Palette.card, borderWidth: 1, borderColor: Palette.border, borderRadius: 14, padding: 14 }, statLabel: { color: Palette.textMuted, fontSize: 9, fontWeight: '700', letterSpacing: 0.5 }, statValue: { color: Palette.greenDark, fontSize: 25, fontWeight: '700', marginTop: 8 }, link: { color: Palette.green, fontSize: 13, fontWeight: '700' }, event: { backgroundColor: Palette.card, borderWidth: 1, borderColor: Palette.border, borderRadius: 14, padding: 14, flexDirection: 'row', alignItems: 'center', marginBottom: 10 }, date: { width: 46, height: 48, borderRadius: 9, backgroundColor: Palette.greenSoft, alignItems: 'center', justifyContent: 'center' }, day: { color: Palette.greenDark, fontSize: 16, fontWeight: '700' }, month: { color: Palette.green, fontSize: 9, fontWeight: '700' }, eventInfo: { flex: 1, marginLeft: 12 }, eventName: { color: Palette.text, fontSize: 15, fontWeight: '700' }, eventMeta: { color: Palette.textSecondary, fontSize: 12, marginTop: 5 }, arrow: { color: Palette.textMuted, fontSize: 24 }, create: { minHeight: 48, backgroundColor: Palette.green, borderRadius: 11, alignItems: 'center', justifyContent: 'center', marginTop: 18 }, createText: { color: '#FFF', fontSize: 15, fontWeight: '700' } });
