import { useFocusEffect, useRouter } from 'expo-router';
import { useCallback, useState } from 'react';
import { Alert, Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { EmptyState, PageIntro } from '@/components/ui-kit';
import { Palette } from '@/constants/theme';
import { useAuth } from '@/context/AuthContext';
import { apiFetch } from '@/lib/api';
import type { EventItem } from '@/types';

export default function MyEventsScreen() {
  const { token } = useAuth(); const router = useRouter(); const [events, setEvents] = useState<EventItem[]>([]);
  const load = useCallback(async () => { if (!token) return; try { setEvents((await apiFetch<{ events: EventItem[] }>('/organizer/events', {}, token)).events); } catch (cause) { Alert.alert('Events unavailable', cause instanceof Error ? cause.message : 'Please try again.'); } }, [token]);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  const remove = (event: EventItem) => Alert.alert('Delete event?', `${event.name} and its bookings will be permanently removed.`, [{ text: 'Keep event', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: () => void apiFetch(`/events/${event.id}`, { method: 'DELETE' }, token ?? undefined).then(load).catch((cause) => Alert.alert('Delete failed', cause instanceof Error ? cause.message : 'Please try again.')) }]);
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><View style={styles.inner}><View style={styles.heading}><PageIntro title="My Events" description="Manage only the events published by your organizer account." /><Pressable onPress={() => router.push('/create-event')} style={styles.add}><Text style={styles.addText}>+ Create</Text></Pressable></View>{events.length ? <View style={styles.list}>{events.map((event) => <View key={event.id} style={styles.card}><Image source={{ uri: event.image }} style={styles.image} /><View style={styles.body}><View style={styles.top}><View style={styles.info}><Text style={styles.name}>{event.name}</Text><Text style={styles.meta}>{event.date} · {event.location}</Text><Text style={styles.meta}>{event.availableSeats}/{event.totalSeats} seats available</Text></View><View style={styles.badge}><Text style={styles.badgeText}>{event.category}</Text></View></View><View style={styles.actions}><Action label="Edit" onPress={() => router.push({ pathname: '/edit-event/[id]', params: { id: event.id } })} /><Action label="Bookings" onPress={() => router.push({ pathname: '/event-bookings/[id]', params: { id: event.id } })} /><Pressable onPress={() => remove(event)} style={styles.delete}><Text style={styles.deleteText}>Delete</Text></Pressable></View></View></View>)}</View> : <EmptyState title="No events published" message="Use Create Event to publish your first listing." />}</View></ScrollView>;
}
function Action({ label, onPress }: { label: string; onPress: () => void }) { return <Pressable onPress={onPress} style={styles.action}><Text style={styles.actionText}>{label}</Text></Pressable>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: Palette.background }, content: { padding: 20, paddingBottom: 36 }, inner: { width: '100%', maxWidth: 680, alignSelf: 'center' }, heading: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' }, add: { backgroundColor: Palette.green, borderRadius: 10, paddingHorizontal: 14, paddingVertical: 11 }, addText: { color: '#FFF', fontSize: 13, fontWeight: '700' }, list: { marginTop: 24, gap: 13 }, card: { backgroundColor: Palette.card, borderWidth: 1, borderColor: Palette.border, borderRadius: 15, overflow: 'hidden' }, image: { width: '100%', height: 135, backgroundColor: Palette.chip }, body: { padding: 15 }, top: { flexDirection: 'row', alignItems: 'flex-start' }, info: { flex: 1 }, name: { color: Palette.text, fontSize: 17, fontWeight: '700' }, meta: { color: Palette.textSecondary, fontSize: 12, marginTop: 5 }, badge: { backgroundColor: Palette.greenSoft, borderRadius: 7, paddingHorizontal: 8, paddingVertical: 5 }, badgeText: { color: Palette.green, fontSize: 10, fontWeight: '700' }, actions: { flexDirection: 'row', gap: 8, borderTopWidth: 1, borderTopColor: Palette.border, marginTop: 14, paddingTop: 13 }, action: { flex: 1, minHeight: 39, borderRadius: 9, backgroundColor: Palette.greenSoft, alignItems: 'center', justifyContent: 'center' }, actionText: { color: Palette.greenDark, fontSize: 12, fontWeight: '700' }, delete: { minHeight: 39, borderRadius: 9, backgroundColor: Palette.errorSoft, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 14 }, deleteText: { color: Palette.error, fontSize: 12, fontWeight: '700' } });
