import { useRouter } from 'expo-router';
import { useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Field, PrimaryButton, initials } from '@/components/ui-kit';
import { Palette } from '@/constants/theme';
import { useAuth } from '@/context/AuthContext';

export default function OrganizerProfileScreen() {
  const router = useRouter(); const { user, logout, updateProfile } = useAuth(); const [editing, setEditing] = useState(false); const [name, setName] = useState(user?.name ?? ''); const [phone, setPhone] = useState(user?.phone ?? ''); const [saving, setSaving] = useState(false);
  if (!user) return null;
  const save = async () => { try { setSaving(true); await updateProfile({ name: name.trim(), phone: phone.trim() }); setEditing(false); Alert.alert('Profile updated', 'Your organizer details have been saved.'); } catch (cause) { Alert.alert('Update failed', cause instanceof Error ? cause.message : 'Please try again.'); } finally { setSaving(false); } };
  const signOut = async () => {
    await logout();
    router.replace('/login' as never);
  };
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><View style={styles.inner}><Text style={styles.title}>Organizer Profile</Text><View style={styles.identity}><View style={styles.avatar}><Text style={styles.initialText}>{initials(user.name)}</Text></View><View style={styles.identityText}><Text style={styles.name}>{user.name}</Text><Text style={styles.role}>EVENT ORGANIZER</Text></View></View><View style={styles.contact}><Text style={styles.label}>EMAIL</Text><Text style={styles.value}>{user.email}</Text><View style={styles.rule} /><Text style={styles.label}>PHONE</Text><Text style={styles.value}>{user.phone || 'No phone number added'}</Text></View>{editing ? <View style={styles.edit}><Text style={styles.editTitle}>Edit organizer profile</Text><Field label="Organizer name" value={name} onChangeText={setName} /><Field label="Phone" value={phone} onChangeText={setPhone} keyboardType="phone-pad" /><PrimaryButton label={saving ? 'Saving...' : 'Save Changes'} onPress={() => void save()} disabled={saving} /><Pressable onPress={() => setEditing(false)} style={styles.dismiss}><Text style={styles.dismissText}>Cancel</Text></Pressable></View> : <View style={styles.menu}><Pressable onPress={() => setEditing(true)} style={styles.item}><Text style={styles.itemText}>Edit Profile</Text><Text style={styles.arrow}>›</Text></Pressable><Pressable onPress={() => void signOut()} style={styles.item}><Text style={[styles.itemText, styles.logout]}>Logout</Text><Text style={[styles.arrow, styles.logout]}>›</Text></Pressable></View>}</View></ScrollView>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: Palette.background }, content: { padding: 20, paddingBottom: 36 }, inner: { width: '100%', maxWidth: 560, alignSelf: 'center' }, title: { color: Palette.text, fontSize: 28, fontWeight: '700' }, identity: { flexDirection: 'row', alignItems: 'center', paddingVertical: 28 }, avatar: { width: 68, height: 68, borderRadius: 34, backgroundColor: Palette.greenDark, alignItems: 'center', justifyContent: 'center' }, initialText: { color: '#FFF', fontSize: 22, fontWeight: '700' }, identityText: { marginLeft: 15 }, name: { color: Palette.text, fontSize: 20, fontWeight: '700' }, role: { color: Palette.green, fontSize: 10, fontWeight: '700', letterSpacing: 1, marginTop: 6 }, contact: { backgroundColor: Palette.card, borderWidth: 1, borderColor: Palette.border, borderRadius: 15, padding: 17 }, label: { color: Palette.textMuted, fontSize: 10, fontWeight: '700', letterSpacing: 0.7 }, value: { color: Palette.text, fontSize: 15, marginTop: 5 }, rule: { height: 1, backgroundColor: Palette.border, marginVertical: 15 }, menu: { backgroundColor: Palette.card, borderWidth: 1, borderColor: Palette.border, borderRadius: 15, overflow: 'hidden', marginTop: 16 }, item: { minHeight: 58, paddingHorizontal: 17, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: Palette.border }, itemText: { color: Palette.text, fontSize: 15, fontWeight: '700' }, arrow: { color: Palette.textMuted, fontSize: 24 }, logout: { color: Palette.error }, edit: { backgroundColor: Palette.card, borderWidth: 1, borderColor: Palette.border, borderRadius: 15, padding: 17, marginTop: 16 }, editTitle: { color: Palette.text, fontSize: 18, fontWeight: '700', marginBottom: 18 }, dismiss: { alignItems: 'center', paddingVertical: 13 }, dismissText: { color: Palette.textSecondary, fontSize: 14, fontWeight: '600' } });
