import { useLocalSearchParams, useRouter } from 'expo-router';
import { useEffect, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { EmptyState, LoadingView, PageIntro, initials } from '@/components/ui-kit';
import { Palette } from '@/constants/theme';
import { useAuth } from '@/context/AuthContext';
import { apiFetch } from '@/lib/api';
import type { Booking, EventItem } from '@/types';

export default function EventBookingsScreen() {
  const { id } = useLocalSearchParams<{ id?: string }>(); const { token } = useAuth(); const router = useRouter(); const [event, setEvent] = useState<EventItem | null>(null); const [bookings, setBookings] = useState<Booking[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { if (!id || !token) return; void Promise.all([apiFetch<{ events: EventItem[] }>('/organizer/events', {}, token), apiFetch<{ bookings: Booking[] }>(`/organizer/events/${id}/bookings`, {}, token)]).then(([eventResult, bookingResult]) => { setEvent(eventResult.events.find((item) => item.id === id) ?? null); setBookings(bookingResult.bookings); }).catch((cause) => Alert.alert('Bookings unavailable', cause instanceof Error ? cause.message : 'Please try again.')).finally(() => setLoading(false)); }, [id, token]);
  if (loading) return <View style={styles.state}><LoadingView label="Loading bookings" /></View>;
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><View style={styles.inner}><Pressable onPress={() => router.back()}><Text style={styles.back}>‹  My Events</Text></Pressable><PageIntro title="Event Bookings" description={event?.name ?? 'Attendee list'} /><View style={styles.summary}><Text style={styles.summaryValue}>{bookings.length}</Text><Text style={styles.summaryLabel}>TOTAL BOOKINGS</Text><Text style={styles.ticketCount}>{bookings.reduce((sum, booking) => sum + booking.numberOfSeats, 0)} tickets reserved</Text></View>{bookings.length ? <View style={styles.list}>{bookings.map((booking) => <View key={booking.id} style={styles.card}><View style={styles.avatar}><Text style={styles.avatarText}>{initials(booking.user?.name)}</Text></View><View style={styles.info}><Text style={styles.name}>{booking.user?.name ?? 'Event attendee'}</Text><Text style={styles.meta}>{booking.user?.email ?? `Booking ${booking.id.slice(-6)}`}</Text><Text style={styles.meta}>{booking.createdAt ? new Date(booking.createdAt).toLocaleDateString() : 'Date unavailable'}</Text></View><View style={styles.right}><Text style={styles.tickets}>{booking.numberOfSeats} ticket{booking.numberOfSeats === 1 ? '' : 's'}</Text><View style={[styles.badge, booking.status === 'CANCELLED' && styles.badgeCancelled]}><Text style={[styles.badgeText, booking.status === 'CANCELLED' && styles.cancelled]}>{booking.status}</Text></View></View></View>)}</View> : <EmptyState title="No bookings yet" message="Attendee reservations for this event will appear here." />}</View></ScrollView>;
}
const styles = StyleSheet.create({ state: { flex: 1, justifyContent: 'center', backgroundColor: Palette.background }, screen: { flex: 1, backgroundColor: Palette.background }, content: { padding: 20, paddingBottom: 36 }, inner: { width: '100%', maxWidth: 640, alignSelf: 'center' }, back: { color: Palette.green, fontSize: 14, fontWeight: '700', marginBottom: 18 }, summary: { backgroundColor: Palette.greenDark, borderRadius: 15, padding: 18, marginTop: 22 }, summaryValue: { color: '#FFF', fontSize: 28, fontWeight: '700' }, summaryLabel: { color: '#D6E6DC', fontSize: 10, fontWeight: '700', letterSpacing: 0.7, marginTop: 3 }, ticketCount: { color: '#FFF', opacity: 0.85, fontSize: 13, marginTop: 12 }, list: { gap: 10, marginTop: 22 }, card: { backgroundColor: Palette.card, borderWidth: 1, borderColor: Palette.border, borderRadius: 14, padding: 14, flexDirection: 'row', alignItems: 'center' }, avatar: { width: 42, height: 42, borderRadius: 21, backgroundColor: Palette.greenSoft, alignItems: 'center', justifyContent: 'center' }, avatarText: { color: Palette.greenDark, fontSize: 14, fontWeight: '700' }, info: { flex: 1, marginLeft: 11 }, name: { color: Palette.text, fontSize: 14, fontWeight: '700' }, meta: { color: Palette.textSecondary, fontSize: 11, marginTop: 3 }, right: { alignItems: 'flex-end' }, tickets: { color: Palette.text, fontSize: 12, fontWeight: '700' }, badge: { backgroundColor: Palette.greenSoft, borderRadius: 6, paddingHorizontal: 7, paddingVertical: 4, marginTop: 7 }, badgeCancelled: { backgroundColor: Palette.errorSoft }, badgeText: { color: Palette.greenDark, fontSize: 9, fontWeight: '700' }, cancelled: { color: Palette.error } });
