import { useState } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { Field, PrimaryButton, SectionHeading } from '@/components/ui-kit';
import { Palette } from '@/constants/theme';
import type { EventItem } from '@/types';

export type EventPayload = { name: string; category: string; description: string; image: string; date: string; time: string; location: string; price: number; totalSeats: number };
const blank = { name: '', category: '', description: '', image: '', date: '', time: '', location: '', price: '', totalSeats: '' };

export function EventForm({ initial, actionLabel, busy, onSubmit }: { initial?: EventItem | null; actionLabel: string; busy?: boolean; onSubmit: (payload: EventPayload) => Promise<void> }) {
  const [form, setForm] = useState(() => initial ? { name: initial.name, category: initial.category, description: initial.description, image: initial.image, date: initial.date, time: initial.time, location: initial.location, price: String(initial.price), totalSeats: String(initial.totalSeats) } : blank); const [error, setError] = useState('');
  const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async () => { const price = Number(form.price); const totalSeats = Number(form.totalSeats); if (!form.name.trim() || !form.category.trim() || form.description.trim().length < 10 || !form.image.trim() || !form.date.trim() || !form.time.trim() || !form.location.trim() || !Number.isFinite(price) || price < 0 || !Number.isInteger(totalSeats) || totalSeats < 1) return setError('Complete every field. The description must be at least 10 characters and seats must be a whole number.'); setError(''); await onSubmit({ name: form.name.trim(), category: form.category.trim(), description: form.description.trim(), image: form.image.trim(), date: form.date.trim(), time: form.time.trim(), location: form.location.trim(), price, totalSeats }); };
  return <ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content}><View style={styles.inner}><SectionHeading title="Basic information" /><View style={styles.group}><Field label="Event name" value={form.name} onChangeText={(v) => update('name', v)} placeholder="Event name" /><Field label="Category" value={form.category} onChangeText={(v) => update('category', v)} placeholder="Music, Business, Arts..." /><Field label="Description" value={form.description} onChangeText={(v) => update('description', v)} placeholder="Tell attendees what to expect" multiline /><Field label="Image URL" value={form.image} onChangeText={(v) => update('image', v)} placeholder="https://..." autoCapitalize="none" /></View><SectionHeading title="Schedule" /><View style={styles.group}><View style={styles.row}><View style={styles.half}><Field label="Date" value={form.date} onChangeText={(v) => update('date', v)} placeholder="YYYY-MM-DD" /></View><View style={styles.half}><Field label="Time" value={form.time} onChangeText={(v) => update('time', v)} placeholder="18:30" /></View></View><Field label="Location" value={form.location} onChangeText={(v) => update('location', v)} placeholder="Venue or address" /></View><SectionHeading title="Ticket information" /><View style={styles.group}><View style={styles.row}><View style={styles.half}><Field label="Price (LKR)" value={form.price} onChangeText={(v) => update('price', v)} keyboardType="numeric" placeholder="2500" /></View><View style={styles.half}><Field label="Total seats" value={form.totalSeats} onChangeText={(v) => update('totalSeats', v)} keyboardType="number-pad" placeholder="50" /></View></View>{error ? <Text style={styles.error}>{error}</Text> : null}<PrimaryButton label={busy ? 'Saving...' : actionLabel} onPress={() => void submit()} disabled={busy} /></View></View></ScrollView>;
}
const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 38 }, inner: { width: '100%', maxWidth: 620, alignSelf: 'center' }, group: { backgroundColor: Palette.card, borderWidth: 1, borderColor: Palette.border, borderRadius: 15, padding: 17 }, row: { flexDirection: 'row', gap: 12 }, half: { flex: 1 }, error: { color: Palette.error, fontSize: 13, lineHeight: 19, marginBottom: 14 } });
