import { useRouter } from 'expo-router';
import { useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Field, PrimaryButton, initials } from '@/components/ui-kit';
import { Palette } from '@/constants/theme';
import { useAuth } from '@/context/AuthContext';

export default function ProfileScreen() {
  const router = useRouter(); const { user, logout, updateProfile } = useAuth(); const [editing, setEditing] = useState(false); const [name, setName] = useState(user?.name ?? ''); const [phone, setPhone] = useState(user?.phone ?? ''); const [saving, setSaving] = useState(false);
  if (!user) return null;
  const save = async () => { try { setSaving(true); await updateProfile({ name: name.trim(), phone: phone.trim() }); setEditing(false); Alert.alert('Profile updated', 'Your details have been saved.'); } catch (cause) { Alert.alert('Update failed', cause instanceof Error ? cause.message : 'Please try again.'); } finally { setSaving(false); } };
  const signOut = async () => {
    await logout();
    router.replace('/login' as never);
  };
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><View style={styles.inner}><Text style={styles.title}>Profile</Text><View style={styles.identity}><View style={styles.avatar}><Text style={styles.initials}>{initials(user.name)}</Text></View><Text style={styles.name}>{user.name}</Text><Text style={styles.email}>{user.email}</Text><Text style={styles.phone}>{user.phone || 'No phone number added'}</Text></View>{editing ? <View style={styles.editCard}><Text style={styles.sectionTitle}>Edit profile</Text><Field label="Name" value={name} onChangeText={setName} /><Field label="Phone" value={phone} onChangeText={setPhone} keyboardType="phone-pad" /><PrimaryButton label={saving ? 'Saving...' : 'Save changes'} onPress={() => void save()} disabled={saving} /><Pressable onPress={() => setEditing(false)} style={styles.cancelEdit}><Text style={styles.cancelEditText}>Cancel</Text></Pressable></View> : <View style={styles.menu}><Pressable style={styles.menuItem} onPress={() => setEditing(true)}><View><Text style={styles.menuTitle}>Edit profile</Text><Text style={styles.menuCopy}>Update your name and phone number</Text></View><Text style={styles.arrow}>›</Text></Pressable><Pressable style={styles.menuItem} onPress={() => void signOut()}><View><Text style={[styles.menuTitle, styles.logout]}>Logout</Text><Text style={styles.menuCopy}>Sign out of this device</Text></View><Text style={[styles.arrow, styles.logout]}>›</Text></Pressable></View>}</View></ScrollView>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: Palette.background }, content: { padding: 20, paddingBottom: 36 }, inner: { width: '100%', maxWidth: 560, alignSelf: 'center' }, title: { color: Palette.text, fontSize: 28, fontWeight: '700' }, identity: { alignItems: 'center', paddingVertical: 32 }, avatar: { width: 76, height: 76, borderRadius: 38, alignItems: 'center', justifyContent: 'center', backgroundColor: Palette.greenSoft, borderWidth: 1, borderColor: Palette.borderStrong }, initials: { color: Palette.greenDark, fontSize: 25, fontWeight: '700' }, name: { color: Palette.text, fontSize: 20, fontWeight: '700', marginTop: 14 }, email: { color: Palette.textSecondary, fontSize: 14, marginTop: 5 }, phone: { color: Palette.textMuted, fontSize: 13, marginTop: 4 }, menu: { backgroundColor: Palette.card, borderWidth: 1, borderColor: Palette.border, borderRadius: 15, overflow: 'hidden' }, menuItem: { minHeight: 72, paddingHorizontal: 17, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: Palette.border }, menuTitle: { color: Palette.text, fontSize: 15, fontWeight: '700' }, menuCopy: { color: Palette.textSecondary, fontSize: 12, marginTop: 4 }, arrow: { color: Palette.textMuted, fontSize: 25 }, logout: { color: Palette.error }, editCard: { backgroundColor: Palette.card, borderWidth: 1, borderColor: Palette.border, borderRadius: 15, padding: 18 }, sectionTitle: { color: Palette.text, fontSize: 19, fontWeight: '700', marginBottom: 18 }, cancelEdit: { alignItems: 'center', paddingVertical: 13 }, cancelEditText: { color: Palette.textSecondary, fontSize: 14, fontWeight: '600' } });
