import { Link, useRouter } from 'expo-router';
import { useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Field, PrimaryButton } from '@/components/ui-kit';
import { Palette } from '@/constants/theme';
import { useAuth } from '@/context/AuthContext';

export default function RegisterScreen() {
  const { register } = useAuth(); const router = useRouter();
  const [form, setForm] = useState({ name: '', email: '', phone: '', password: '' }); const [role, setRole] = useState<'USER' | 'ORGANIZER'>('USER'); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState('');
  const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async () => { if (!form.name.trim() || !form.email.trim() || form.password.length < 6) return setError('Add your name, a valid email, and a password of at least 6 characters.'); try { setSubmitting(true); setError(''); await register(form.name.trim(), form.email.trim(), form.password, role, form.phone.trim() || undefined); router.replace('/' as never); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to create account.'); } finally { setSubmitting(false); } };
  return <KeyboardAvoidingView style={styles.screen} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView contentContainerStyle={styles.scroll} keyboardShouldPersistTaps="handled"><View style={styles.content}><Text style={styles.kicker}>JOIN EVENTHUB</Text><Text style={styles.title}>Create your account</Text><Text style={styles.copy}>Choose how you plan to use EventHub. Your workspace will be tailored to that role.</Text><View style={styles.form}><Field label="Full name" value={form.name} onChangeText={(v) => update('name', v)} placeholder="Your name" /><Field label="Email address" value={form.email} onChangeText={(v) => update('email', v)} keyboardType="email-address" autoCapitalize="none" placeholder="you@example.com" /><Field label="Phone (optional)" value={form.phone} onChangeText={(v) => update('phone', v)} keyboardType="phone-pad" placeholder="+94..." /><Field label="Password" value={form.password} onChangeText={(v) => update('password', v)} secureTextEntry placeholder="At least 6 characters" /><Text style={styles.roleLabel}>Account type</Text><View style={styles.roles}>{(['USER', 'ORGANIZER'] as const).map((item) => <Pressable key={item} onPress={() => setRole(item)} style={[styles.role, role === item && styles.roleActive]}><Text style={[styles.roleText, role === item && styles.roleTextActive]}>{item === 'USER' ? 'Attend events' : 'Organize events'}</Text></Pressable>)}</View>{error ? <Text style={styles.error}>{error}</Text> : null}<PrimaryButton label={submitting ? 'Creating account...' : 'Register'} onPress={() => void submit()} disabled={submitting} /></View><View style={styles.linkRow}><Text style={styles.muted}>Already have an account?</Text><Link href="/login" asChild><Pressable><Text style={styles.link}>Login</Text></Pressable></Link></View></View></ScrollView></KeyboardAvoidingView>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: Palette.background }, scroll: { flexGrow: 1, justifyContent: 'center', padding: 24 }, content: { width: '100%', maxWidth: 500, alignSelf: 'center', paddingVertical: 24 }, kicker: { color: Palette.green, fontSize: 12, fontWeight: '700', letterSpacing: 1.2 }, title: { color: Palette.text, fontSize: 28, fontWeight: '700', marginTop: 7 }, copy: { color: Palette.textSecondary, fontSize: 15, lineHeight: 22, marginTop: 8, marginBottom: 24 }, form: { backgroundColor: Palette.card, borderWidth: 1, borderColor: Palette.border, borderRadius: 16, padding: 20 }, roleLabel: { color: Palette.text, fontSize: 13, fontWeight: '600', marginBottom: 8 }, roles: { flexDirection: 'row', gap: 8, marginBottom: 18 }, role: { flex: 1, minHeight: 42, borderRadius: 10, borderWidth: 1, borderColor: Palette.borderStrong, alignItems: 'center', justifyContent: 'center', backgroundColor: Palette.card }, roleActive: { backgroundColor: Palette.greenSoft, borderColor: Palette.green }, roleText: { color: Palette.textSecondary, fontSize: 13, fontWeight: '600' }, roleTextActive: { color: Palette.greenDark }, error: { color: Palette.error, fontSize: 13, lineHeight: 19, marginBottom: 14 }, linkRow: { flexDirection: 'row', justifyContent: 'center', gap: 6, marginTop: 22 }, muted: { color: Palette.textSecondary, fontSize: 14 }, link: { color: Palette.green, fontSize: 14, fontWeight: '700' } });
