import { useLocalSearchParams, useRouter } from 'expo-router';
import { useEffect, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { EmptyState, LoadingView } from '@/components/ui-kit';
import { Palette } from '@/constants/theme';
import { useAuth } from '@/context/AuthContext';
import { apiFetch } from '@/lib/api';
import type { Booking } from '@/types';

export default function BookingDetailScreen() {
  const { id } = useLocalSearchParams<{ id?: string }>(); const { token } = useAuth(); const router = useRouter(); const [booking, setBooking] = useState<Booking | null>(null); const [loading, setLoading] = useState(true);
  useEffect(() => { if (!id || !token) return; void apiFetch<{ bookings: Booking[] }>('/bookings/my', {}, token).then((r) => setBooking(r.bookings.find((item) => item.id === id) ?? null)).finally(() => setLoading(false)); }, [id, token]);
  if (loading) return <View style={styles.state}><LoadingView label="Loading booking" /></View>;
  if (!booking) return <View style={styles.state}><EmptyState title="Booking unavailable" message="This reservation could not be found." /></View>;
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><View style={styles.inner}><Pressable onPress={() => router.back()}><Text style={styles.back}>‹  My Bookings</Text></Pressable><Text style={styles.kicker}>BOOKING DETAILS</Text><Text style={styles.title}>{booking.event?.name ?? 'Event booking'}</Text><View style={styles.ticket}><View style={styles.status}><Text style={styles.statusText}>{booking.status}</Text></View><Row label="Event date" value={booking.event?.date ?? 'Unavailable'} /><Row label="Event time" value={booking.event?.time ?? 'Unavailable'} /><Row label="Location" value={booking.event?.location ?? 'Unavailable'} /><View style={styles.rule} /><Row label="Ticket quantity" value={String(booking.numberOfSeats)} /><Row label="Price per ticket" value={`LKR ${((booking.event?.price ?? booking.totalAmount / booking.numberOfSeats)).toLocaleString()}`} /><View style={styles.totalRow}><Text style={styles.totalLabel}>Total paid</Text><Text style={styles.total}>LKR {booking.totalAmount.toLocaleString()}</Text></View><Text style={styles.reference}>Reference: {booking.id}</Text></View></View></ScrollView>;
}
function Row({ label, value }: { label: string; value: string }) { return <View style={styles.row}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>; }
const styles = StyleSheet.create({ state: { flex: 1, justifyContent: 'center', backgroundColor: Palette.background }, screen: { flex: 1, backgroundColor: Palette.background }, content: { padding: 20, paddingBottom: 36 }, inner: { width: '100%', maxWidth: 560, alignSelf: 'center' }, back: { color: Palette.green, fontSize: 14, fontWeight: '700', marginBottom: 28 }, kicker: { color: Palette.green, fontSize: 11, fontWeight: '700', letterSpacing: 1 }, title: { color: Palette.text, fontSize: 27, lineHeight: 33, fontWeight: '700', marginTop: 7 }, ticket: { backgroundColor: Palette.card, borderWidth: 1, borderColor: Palette.border, borderRadius: 16, padding: 18, marginTop: 24 }, status: { alignSelf: 'flex-start', backgroundColor: Palette.greenSoft, borderRadius: 7, paddingHorizontal: 8, paddingVertical: 5, marginBottom: 17 }, statusText: { color: Palette.greenDark, fontSize: 10, fontWeight: '700' }, row: { flexDirection: 'row', justifyContent: 'space-between', gap: 20, paddingVertical: 9 }, label: { color: Palette.textSecondary, fontSize: 14 }, value: { color: Palette.text, fontSize: 14, fontWeight: '600', textAlign: 'right', flex: 1 }, rule: { height: 1, backgroundColor: Palette.border, marginVertical: 9 }, totalRow: { flexDirection: 'row', justifyContent: 'space-between', borderTopWidth: 1, borderTopColor: Palette.border, marginTop: 10, paddingTop: 17 }, totalLabel: { color: Palette.text, fontSize: 15, fontWeight: '700' }, total: { color: Palette.greenDark, fontSize: 17, fontWeight: '700' }, reference: { color: Palette.textMuted, fontSize: 10, marginTop: 22 } });
